In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter = ',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:,4]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features = data[:,0:4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X = features
y = labels

In [11]:
#Split the data

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
len(x)

NameError: name 'x' is not defined

In [15]:
len(X)

1372

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_x_train = scaler_object.transform(X_train)

In [21]:
scaled_x_test = scaler_object.transform(X_test)

In [22]:
#MODEL BUILD

In [23]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
model = Sequential()

model.add(Dense(4,input_dim = 4, activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [25]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [26]:
#Tran the data

In [27]:
model.fit(scaled_x_train, y_train, epochs = 50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.6486 - acc: 0.6333
Epoch 2/50
 - 0s - loss: 0.6346 - acc: 0.6888
Epoch 3/50
 - 0s - loss: 0.6202 - acc: 0.7367
Epoch 4/50
 - 0s - loss: 0.6069 - acc: 0.7584
Epoch 5/50
 - 0s - loss: 0.5917 - acc: 0.7661
Epoch 6/50
 - 0s - loss: 0.5687 - acc: 0.7758
Epoch 7/50
 - 0s - loss: 0.5473 - acc: 0.7911
Epoch 8/50
 - 0s - loss: 0.5296 - acc: 0.7965
Epoch 9/50
 - 0s - loss: 0.5133 - acc: 0.7965
Epoch 10/50
 - 0s - loss: 0.4986 - acc: 0.8030
Epoch 11/50
 - 0s - loss: 0.4843 - acc: 0.8096
Epoch 12/50
 - 0s - loss: 0.4718 - acc: 0.8161
Epoch 13/50
 - 0s - loss: 0.4578 - acc: 0.8292
Epoch 14/50
 - 0s - loss: 0.4449 - acc: 0.8281
Epoch 15/50
 - 0s - loss: 0.4324 - acc: 0.8357
Epoch 16/50
 - 0s - loss: 0.4204 - acc: 0.8390
Epoch 17/50
 - 0s - loss: 0.4091 - acc: 0.8509
Epoch 18/50
 - 0s - loss: 0.3980 - acc: 0.8531
Epoch 19/50
 - 0s - loss: 0.3874 - acc: 0.8618
Epoch 20/50
 - 0s - loss: 0.3772 - acc: 0.8651
Epoch 21/50
 - 0s - loss: 0.3674 - acc: 0.8672
Epoch 22/50
 - 0s - lo

In [29]:
model.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [30]:
model.metrics_names

['loss', 'acc']

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

In [32]:
predictions = model.predict_classes(scaled_x_test)

In [33]:
confusion_matrix(y_test, predictions)

array([[252,   5],
       [ 21, 175]], dtype=int64)

In [34]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.92      0.98      0.95       257
        1.0       0.97      0.89      0.93       196

avg / total       0.94      0.94      0.94       453



In [35]:
model.save('mysupermodel.h5')

In [36]:
from keras.models import load_model

In [37]:
newmodel = load_model('mysupermodel.h5')

In [38]:
newmodel.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    